#!/usr/bin/env bash
# Wrapper for `python -m openwakeword.train ...` that exposes torch's
# bundled CUDA 12 libs (cublas/cudnn/curand/...) to onnxruntime-gpu.
# Generated by install_training.sh.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="${VENV:-$HERE/.venv}"
NV_LIB_PATH="$("$VENV/bin/python" -c '
import os, glob, nvidia
nv_dir = os.path.dirname(nvidia.__file__)
print(":".join(sorted(set(os.path.dirname(p) for p in glob.glob(f"{nv_dir}/*/lib/*.so*")))))
')"
export LD_LIBRARY_PATH="$NV_LIB_PATH:${LD_LIBRARY_PATH:-}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
exec "$VENV/bin/python" -m openwakeword.train "$@"
